import { Inter } from "next/font/google";
import { AppWrapper } from "@/components/dashboard/AppWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Coalesy - NFT event ticketing platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppWrapper>{children}</AppWrapper>
      </body>
    </html>
  );
}
